# Generated by Django 5.2.9 on 2025-12-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_test_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_students',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A (90-100)'), ('B', 'B (80-89)'), ('C', 'C (70-79)'), ('D', 'D (60-69)'), ('F', 'F (Below 60)'), ('', 'Not Graded')], default='', max_length=2)),
                ('score', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='university.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='university.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
